### ISSUE TITLE
global keybord events

### ISSUE THREAD

**Issue by obonyojimmy** [eiannone/keyboard#1]
Hi , testing this seems the keyboard events are sandboxed to the console only , how does one enable global keyboard events ?

**Comment by eiannone** [comment]
Hi, the program listen to console events only, sorry. If you need to get keystrokes globally, take a look here: http://stackoverflow.com/questions/38646794/implement-a-global-hotkey-in-golang

**Comment by obonyojimmy** [comment]
Thanks alot for the pointer.
