### ISSUE TITLE
crash on few characters in loop

### ISSUE THREAD

**Issue by network4all** [eiannone/keyboard#11]
code:
	err = kb.Open()
	if err != nil {
		panic(err)
	}
	defer kb.Close()

	keyboard := make(chan string)
	go func(keyboard chan string) {
		for {
			char, _, err := kb.GetSingleKey()
			if err != nil {
				panic(err)
			}
			fmt.Printf("You pressed: %q\r\n", char)
			keyboard <- string(char)
		}
	}(keyboard)

output:
-------------------------------------------

You pressed: '1'
You pressed: '2'
You pressed: '3'
panic: runtime error: slice bounds out of range

goroutine 33 [running]:
github.com/eiannone/keyboard.initConsole.func1()
        /Users/kuinda01/Documents/go/src/github.com/eiannone/keyboard/keyboard.go:193 +0x2af
created by github.com/eiannone/keyboard.initConsole
        /Users/kuinda01/Documents/go/src/github.com/eiannone/keyboard/keyboard.go:182 +0x31a
exit status 2

**Comment by snaggen** [comment]
If we look at the code where this happens

`

                    n, err := syscall.Read(in, buf)
                    if err == unix.EAGAIN || err == unix.EWOULDBLOCK {
                        break
                    }
                    select {
                    case input_buf <- input_event{buf[:n], err}:
                        continue
                    case <-quit:
                        return
                   }
`

we can see that in the case were Read returns any error besides EAGAIN and EWOULDBLOCK it will not be handled. In these cases n will be set to -1 as per the linux read syscall documentation. So what happens is that we try to access buf at pos -1.
