### ISSUE TITLE
Submitting for x/term

### ISSUE THREAD

**Issue by techtonik** [eiannone/keyboard#3]
For me that would be a worthy addition to new `x/term` package in go. How do you think?

**Comment by eiannone** [comment]
Do you mean https://github.com/golang/term repository as `x/term`? (please excuse me for the dumb question, I'm an absolute novice in Go language).
Anyway, before adding this code to an official package, shouldn't we support also other OS?

**Comment by techtonik** [comment]
I am a novice in Go too. =) Yes, this is the repository, although the location [to submit code](https://golang.org/doc/contribute.html) is https://go.googlesource.com/term/

**Comment by techtonik** [comment]
Getting support for other OS is hard to do by one man army, If I am not proficient in Linux terminals, it should not stop me from submitting work for Windows and vice versa. And also it is easier to review in chunks.

`x/term` is too new, so making small steps at a time should be ok. For example I don't know how to detect if stdin file descriptor is a console/terminal, so I submitted only Linux part for now. https://go-review.googlesource.com/c/38050/ I rely on review comments from experienced contributors to guide me further.

**Comment by eiannone** [comment]
Ok, I submitted the code for review: https://go-review.googlesource.com/c/38062/
Meanwhile I've added also unix support!

**Comment by techtonik** [comment]
Ahh. If there is substantial amount of code copied from termbox-go, this creates a legal problem that they must also sigh a CLA, and their copyright line should be present in
https://github.com/eiannone/keyboard/blob/master/LICENSE

**Comment by eiannone** [comment]
I don't know if the code I used can be considered or not a "substantial portion" of original. Anyway, now I've added copyright notice both here and on x/term project.

**Comment by techtonik** [comment]
I believe it needs an issue in https://github.com/golang/go/issues to find reviewers to start up the process.
