### ISSUE TITLE
Panic on flood!

### ISSUE THREAD

**Issue by paemuri** [eiannone/keyboard#4]
Hello! 😄 

I am using your library for a small [project of mine](https://github.com/Nhanderu/dois-mil/tree/a974303f929ebf5539f31e89d2ee35c8bac4acac). The problem is that, everytime I flood the stdin with random keys, the program panics.

The output:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
github.com/eiannone/keyboard.Close()
        .../src/github.com/eiannone/keyboard/keyboard_windows.go:293 +0xcc
github.com/eiannone/keyboard.GetSingleKey(0x0, 0x4, 0x8)
        .../src/github.com/eiannone/keyboard/keyboard_windows.go:318 +0x8b
main.main()
        .../src/github.com/Nhanderu/dois-mil/main.go:33 +0x104

goroutine 20 [chan send]:
github.com/eiannone/keyboard.inputEventsProducer()
        .../src/github.com/eiannone/keyboard/keyboard_windows.go:253 +0x316
created by github.com/eiannone/keyboard.Open
        .../src/github.com/eiannone/keyboard/keyboard_windows.go:279 +0x22c
```

It is not a huge problem for me, but it is always worth pointing it out. 😉

**Comment by eiannone** [comment]
You are using the library incorrectly. You should replace at [line 35](https://github.com/Nhanderu/dois-mil/blob/master/cmd/dois-mil/main.go#L35):

`_, key, err := keyboard.GetSingleKey()`

with:

`_, key, err := keyboard.GetKey()`

`GetSingleKey()` function is supposed to be used only when you need a single key. It automatically opens console, waits for a key and then closes it.

I suggest also to substitute, at line 49, `break` with `return`.

**Comment by eiannone** [comment]
Anyway, I've also updated the code to prevent deadlocks like this, even when using improperly `GetSingleKey()` function.
So, if my previous suggestion doesn't work, try updating the library, with 
`go get -u github.com/eiannone/keyboard`

**Comment by paemuri** [comment]
> `GetSingleKey()` function is supposed to be used only when you need a single key. It automatically opens console, waits for a key and then closes it.

I understand now!
So, instead of calling `GetSingleKey` everytime, I should `Open`, call `GetKey` everytime I need, and then `Close`.
Thank you!

> I suggest also to substitute, at line 49, break with return.

I have already changed that, but thanks! 😄
