### ISSUE TITLE
Incorrectly processed keys "up" "down" "left" "right" in Linux

### ISSUE THREAD

**Issue by kirsrus** [eiannone/keyboard#5]
_(Via Google translate)_

Hello.
I'm trying to use your project. Faced a problem.
Incorrectly processed keys `up` `down` `left` `right` in Linux (Mint).
Example:

```go
keyboard.Open()
defer keyboard.Close()
for {
	char, key, _ := keyboard.GetKey()
	fmt.Printf("<%d 0x%x \"%s\" key: %d\n", char, char, string(char), key)
}
```

```term
// Press A - OK
65 0x41 "A" key: 0
// Press ESC - OK
0 0x0 "" key: 27
// Press Left - ERROR
0 0x0 "" key: 27
// Press Left - ERROR
91 0x5b "[" key: 0
// Press Left - ERROR
68 0x44 "D" key: 0
// Press A
0 0x0 "" key: 27
```

**Comment by eiannone** [comment]
Probably your terminal is not yet supported. Could you please run the command `printenv TERM` from the shell and tell me the result?

**Comment by eiannone** [comment]
I've just added support for xterm-256color terminal (Ubuntu). Maybe this commit could fix also this issue. Could you update keyboard library and try again?

**Comment by kirsrus** [comment]
I renewed. All without changes:

```term
$ printenv TERM
xterm

$ go run main.go
// Press Left:
<0 0x0 "" key: 27
// Press Up:
<91 0x5b "[" key: 0
// Press Right:
<68 0x44 "D" key: 0
// Press Down:
<0 0x0 "" key: 27
```

And I found another failure, already in the terminal `Ctrl + Alt + F1`.
Everything works until I press the `Ctrl+Break` key combination:

```term
$ printenv TERM
linux

$ go run main.go

// Press Left - ok:
<0 0x0 "" key: 65515
// Press Up - ok:
<0 0x0 "" key: 65517
// Press Right - ok:
<0 0x0 "" key: 65514
// Press Down - ok:
<0 0x0 "" key: 65516
// Press Ctrl + Break
<0 0x0 "" key: 27
// Press Left - not ok, it should be 65515:
<91 0x5b "[" key: 0
// Press Up - not ok, it should be 65517:
<80 0x50 "P" key: 0
// Press Right - not ok, it should be 65514:
<0 0x0 "" key: 65515
// Press Down - not ok, , it should be 65516:
<0 0x0 "" key: 65517
```

**Comment by eiannone** [comment]
I see you get two different results when running `printenv TERM` command. First time you get "xterm", and second time "linux". 
Are you using two different terminals?

**Comment by kirsrus** [comment]
I checked in two different terminals to compare the result.
"Xterm" is from the Linux Mint GUI, "linux" is the text console by `Ctrl + Alt + F1`. In the "linux" terminal, everything works out right, but accidentally found a problem there (when you press Ctrl + Break).

**Comment by kirsrus** [comment]
I do not have enough knowledge to correct these problems. If you need additional tests - give me your code and I'll try to execute them. If you have time and interest in this.

**Comment by eiannone** [comment]
I've updated the code trying to fix the first problem with xterm (GUI console). Could you please update the package and try again?
As regarding the second issue (Ctrl + Break combination), that particular key currently is not supported. I will try to improve the code to at least do not mess up when that key is received.

**Comment by eiannone** [comment]
Ok, with my [latest commit](/eiannone/keyboard/commit/13c6922964cb22d2cf5d49884b265b06ec67643a) now it returns "Esc" whenever it encounters an unknown key combination, so it should partially fix your second issue, because it will not break when you press an unsupported key.
Unfortunately, every Linux terminal has its own escape sequence for any special key, so it would require a lot of work for me to take into account for all possible key combinations in all possibile terminal environments.

**Comment by kirsrus** [comment]
Working! Checked on all available terminals.
The fact that `ESC` returns is a good solution in my opinion, since it was this that broke all subsequent input of data from the keyboard.
Thank you!
