### ISSUE TITLE
A problem with the keyboard.GetSingleKey() method

### ISSUE THREAD

**Issue by kirsrus** [eiannone/keyboard#6]
Hello again!
Already updated your module to the latest version.
A problem with the keyboard.GetSingleKey() method:
```go
for {
    ch, key, err := keyboard.GetSingleKey()
    if err != nil {
        log.Fatal(err)
    }
    fmt.Printf("%v %v\n", ch, key)
}
```
I consistently press the LEFT, UP, RIGHT, DOWN keys after starting the program:
```term
// Press LEFT - ok
0 65515
// Press UP - ok
0 65517
// Press RIGHT - not ok
0 65514
0 65514    <-- Duplicate
// Press DOWN - not ok
0 65516
0 65516    <-- Duplicate
// Press LEFT - not ok
0 65515
0 65515    <-- Duplicate
0 65515    <-- Duplicate
// Etc.
0 65517    <-- Press UP
0 65517
0 65517
0 65517
0 65514    <-- Press RIGHT
0 65514
0 65514
0 65514
0 65514
0 65514
0 65516    <-- Press DOWN
0 65516
0 65516
0 65516
0 65516
0 65516
0 65516
0 65516
0 65516
0 65515    <-- Press LEFT
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
0 65515
panic: runtime error: slice bounds out of range

goroutine 15 [running]:
github.com/eiannone/keyboard.initConsole.func1()
	/home/kirs/go/src/github.com/eiannone/keyboard/keyboard.go:194 +0x383
created by github.com/eiannone/keyboard.initConsole
	/home/kirs/go/src/github.com/eiannone/keyboard/keyboard.go:205 +0x336
```
In the terminal "linux":

    // Press Left
    0 65515
    panic: runtime error: slice bounds out of range
    
    goroutine 7 [running]:
    github.com/eiannone/keyboard.initConsole.func1()
    	/home/kirs/go/src/github.com/eiannone/keyboard/keyboard.go:194 +0x383
    created by github.com/eiannone/keyboard.initConsole
    	/home/kirs/go/src/github.com/eiannone/keyboard/keyboard.go:205 +0x336

In the Windows terminal, there is no such problem.

**Comment by eiannone** [comment]
I'm sorry for delay in replying. This bug should be fixed with my latest commit a263abc743117abfada48e90372473b551115a7f
I would be glad if you can confirm that it solves your problem. Thank you

**Comment by kirsrus** [comment]
I checked on all consoles available to me - the problem was gone.
Thank you!

**Comment by eiannone** [comment]
Great!
